---
output:
  word_document: default
  keep_tex: false
---

# \pagenumbering{gobble}

```{r setup, include = FALSE}
#   pdf_document: default
# render('C:/Users/csave/Desktop/2017-06-12/report.Rmd', output_file = "report_default_speed_permutations.pdf")
# render('C:/Users/csave/Desktop/2017-06-12/report.Rmd', output_file = "report_grid6x6_speed_permutations.pdf")
# render('C:/Users/csave/Desktop/2017-06-12/report.Rmd', output_file = "report_grid8x8_speed_permutations.pdf")
# render('C:/Users/csave/Desktop/2017-06-12/report.Rmd', output_file = "report_random1_speed_permutations.pdf")
# render('C:/Users/csave/Desktop/2017-06-12/report.Rmd', output_file = "report_random2_speed_permutations.pdf")

#   word_document: default
knitr::opts_chunk$set(echo = TRUE, 
                      fig.align = 'center',
                      fig.width = 5, fig.height = 5)
```

```{r city, echo = FALSE}
plot(ci, edge.label.ids = FALSE)
```

```{r scatter, echo = FALSE}
plot(getROAHBenefitsWithTax(sim_fixed, tau)[7, ], 
     getROAHBenefitsWithTax(sim, tau)[7, ], xlab = "F", ylab = "NF")
abline(0, 1)
```

```{r bc ratios, echo = FALSE}
# 100 million SEK/km
# 260 work days per year
# 40 years
# 4% discounting rate
budget <- 8000 #20*228
ckm <- (1000/228)*100/(1.04^40)
index <- match(getTotalBenefitsGivenBudget(sim_fixed, tau, ckm)[ , "Scenario"], getTotalBenefitsGivenBudget(sim, tau, ckm))
wwg <- getTotalBenefitsGivenBudget(sim, tau, ckm)[index, ]
accc <- cumsum(wwg[-1 , "C"])
accb <- cumsum(wwg[-1 , "B"])
wwg[-1 , 6] <- accc
wwg[-1 , 7] <- accb
nf <- getTotalBenefitsGivenBudget(sim, tau, ckm)
plot(getTotalBenefitsGivenBudget(sim, tau, ckm)[ , "ACC C"], getTotalBenefitsGivenBudget(sim, tau, ckm)[ , "ACC B"], type = "l", xlab = "AC", ylab = "AB", col = "red")
lines(getTotalBenefitsGivenBudget(sim_fixed, tau, ckm)[ , "ACC C"], getTotalBenefitsGivenBudget(sim_fixed, tau, ckm)[ , "ACC B"], type = "l", col = "blue")
lines(wwg[ , "ACC C"], wwg[ , "ACC B"], type = "l", col = "black")
#abline(v = budget, lty = 2, col = "gray60")
#text(budget, 0, "Budget constraint", col = "gray60", adj = c(-0.1, 0))
legend("topleft", 
       c("NF", "F", "Planner"), 
       lty = c(0, 0), col = c("red", "blue", "black"), pch = 15)
```

```{r benefit loss, echo = FALSE}
#wwg[wwg[, "ACC C"] < budget, ]
#nf[nf[, "ACC C"] < budget, ]
#diff <- nf[nf[, "ACC C"] < budget, "ACC B"]-wwg[wwg[, "ACC C"] < budget, "ACC B"]
#diff <- nf[ , "ACC B"]-wwg[ , "ACC B"]
#avg.diff <- mean(nf[ , "ACC B"]-wwg[ , "ACC B"])
#plot(diff, type = "b", xlab = "Ordered scenario", ylab = "Accumulated benefits difference")
#abline(a = avg.diff, b = 0, lty = 3)
```

```{r, echo = FALSE}
x <- nf[ , "ACC C"]
y <- nf[ , "ACC B"]
x2 <- wwg[ , "ACC C"]
y2 <- wwg[ , "ACC B"]
constf<-approxfun(x, y, method = "linear")
constf2<-approxfun(x2, y2, method = "linear")
constdiff <- function(x) {constf(x)-constf2(x)}
vals <- constdiff(seq(from = 0, to = 80000, length.out = 80000))
avg.diff <- mean(vals, na.rm = TRUE)
cum.avg <- cumsum(vals)/seq_along(vals)
curve(constdiff, from = 0, to = 80000, n = 80000, xlab = "Budget", ylab = "Accumulated benefits difference")
lines(cum.avg, col = "blue")
abline(a = avg.diff, b = 0, lty = 3)
```

```{r, echo = FALSE}
x <- nf[ , "ACC C"]
y <- nf[ , "ACC B"]
x2 <- wwg[ , "ACC C"]
y2 <- wwg[ , "ACC B"]
x3 <- getTotalBenefitsGivenBudget(sim_fixed, tau, ckm)[ , "ACC C"]
y3 <- getTotalBenefitsGivenBudget(sim_fixed, tau, ckm)[ , "ACC B"]
plot(nf[ , "ACC C"], nf[ , "ACC B"], type = "n", xlab = "AC", ylab = "AB")
segments(x[-length(x)], y[-length(x)], x[-1], y[-length(x)], col = "red") 
points(x[-length(x)], y[-length(x)], pch = 16, cex = 0.3, col = "red")
points(x[-1], y[-length(x)], pch = 1, cex = 0.3, col = "red") 
segments(x2[-length(x2)], y2[-length(x2)], x2[-1], y2[-length(x2)], col = "black") 
points(x2[-length(x2)], y2[-length(x2)], pch = 16, cex = 0.3, col = "black")
points(x2[-1], y2[-length(x2)], pch = 1, cex = 0.3, col = "black") 
segments(x3[-length(x3)], y3[-length(x3)], x3[-1], y3[-length(x3)], col = "blue") 
points(x3[-length(x3)], y3[-length(x3)], pch = 16, cex = 0.3, col = "blue")
points(x3[-1], y3[-length(x3)], pch = 1, cex = 0.3, col = "blue") 
legend("topleft", 
       c("NF", "F", "Planner"), 
       lty = c(0, 0), col = c("red", "blue", "black"), pch = 15)
```

```{r, echo = FALSE}
constf<-approxfun(x, y, method = "constant")
constf2<-approxfun(x2, y2, method = "constant")
constdiff <- function(x) {constf(x)-constf2(x)}
vals <- constdiff(seq(from = 0, to = 80000, length.out = 80000))
avg.diff <- mean(vals, na.rm = TRUE)
cum.avg <- cumsum(vals)/seq_along(vals)
curve(constdiff, from = 0, to = 80000, n = 80000, xlab = "Budget", ylab = "Accumulated benefits difference")
lines(cum.avg, col = "blue")
abline(a = avg.diff, b = 0, lty = 3)
```


```{r boxplot, echo = FALSE}
benefits <- getROAHBenefitsWithTax(sim, tau)[c(1,2,4,5,6), -1]
benefits_f <- getROAHBenefitsWithTax(sim_fixed, tau)[c(1,2,4,5,6), -1]
colnames(benefits) <- colnames(benefits, do.NULL = FALSE, prefix = "Sim.")
colnames(benefits_f) <- colnames(benefits_f, do.NULL = FALSE, prefix = "Sim.")
benefits <- cbind(LU = "NF", benefits)
benefits_f <- cbind(LU = "F", benefits_f)
benefits <- cbind(Variable = rownames(benefits), benefits)
benefits_f <- cbind(Variable = rownames(benefits_f), benefits_f)
rownames(benefits_f) <- rownames(benefits) <- NULL
df <- merge(benefits, benefits_f, all = TRUE)
for (i in 1:(dim(df)[2]-2)) {df[, (i+2)] <- as.numeric(as.character(df[, (i+2)]))}
df <- melt(df)
boxplot(formula = value ~ Variable, data = df, subset = LU == "NF",
        col = "red",
        boxwex  = 0.25,
        at = 1:5 - 0.2,
        ylim = c(floor(min(df$value))-1, ceiling(max(df$value))+1),
        xaxt = "n",
        frame.plot = TRUE)
boxplot(formula = value ~ Variable, data = df, subset = LU == "F", 
        col = "blue",
        boxwex = 0.25,
        at = 1:5 + 0.2,
        xaxt = "n",
        add = TRUE)
axis(side = 1, at =  1:5, labels = c("TC", "LP", "TR", "TT", "WR"))
legend("topleft", 
       c("NF", "F"), 
       lty = c(0, 0), col = c("red", "blue"), pch = 15)
```

```{r spline, echo = FALSE}
spline <- smooth.spline(getRanking(sim, tau)[2, ], getRanking(sim, tau)[4, ])
spline_fixed <- smooth.spline(getRanking(sim_fixed, tau)[2, ], getRanking(sim_fixed, tau)[4, ])
plot(getRanking(sim, tau)[2, ], getRanking(sim, tau)[4, ], xlab = "Total link betweenness centrality", ylab = "Benefits, incl. tax revenue changes, per km", col = "red")
points(getRanking(sim_fixed, tau)[2, ], getRanking(sim_fixed, tau)[4, ], col = "blue")
lines(spline, col = "red")
lines(spline_fixed, col = "blue")
legend("topleft", 
       legend = c("NF", "F"), 
       lty = c(1,1), col = c("red", "blue"), pch = 15)
```

```{r plots, echo = FALSE}
plot(sim, type = "argmax", main = "Time spent at work (NF)", xlab = "hours", index = 1)
plot(sim, type = "argmax", main = "Travel time (NF)", xlab = "hours", index = 5)
plot(sim, type = "vkt", main = "Vehicle Kilometers Travelled (NF)", xlab = "km")
plot(sim, type = "argmax", main = "Land use (NF)", xlab = ~"km"^2, index = 4)
plot(sim, type = "wagerate", main = "Wage rate (NF)", xlab = ~"SEK/hour")
```
```{r plots fixed, echo = FALSE}
plot(sim_fixed, type = "argmax", main = "Time spent at work (F)", xlab = "hours", index = 1)
plot(sim_fixed, type = "argmax", main = "Travel time (F)", xlab = "hours", index = 5)
plot(sim_fixed, type = "vkt", main = "Vehicle Kilometers Travelled (F)", xlab = "km")
plot(sim_fixed, type = "argmax", main = "Land use (F)", xlab = ~"km"^2, index = 4)
plot(sim_fixed, type = "wagerate", main = "Wage rate (F)", xlab = ~"SEK/hour")
```

```{r residential density, echo = FALSE}
persp3D(sim,
        type = "residence",
        sid = 1,
        linear = FALSE,
        zlab = "Residential density",
        sub = "Base scenario")
```

```{r work force density, echo = FALSE}
persp3D(sim,
        type = "work",
        sid = 1,
        linear = FALSE,
        zlab = "Worker density",
        sub = "Base scenario")
```

```{r income, echo = FALSE}
persp3D(sim,
        type = "income",
        sid = 1,
        linear = FALSE,
        zlab = "Average destination income, pre-tax",
        sub = "Base scenario")
```

```{r price, echo = FALSE}
persp3D(sim,
        type = "landprice",
        sid = 1,
        linear = FALSE,
        zlab = "Land price",
        sub = "Base scenario")
```