output$economyShow <- renderPrint({
  return(print(economyInput()))
})

output$weightsShow <- renderPrint({
  return(print(networkWeightsInput()))
})

output$summary_economy <- renderPrint({
  if (is.null(simulateEconomyInput())) return(invisible(NULL))
  digits <- 4
  cat("[NON-FIXED LAND-USE RESULTS] \n \n")
  if (input$showConvergenceMessage) getConvergenceMessages(simulateEconomyInput())
  cat("\n Elasticities of VKT w.r.t. ... \n")
  print(getVKTAccessibility(simulateEconomyInput()), digits = digits)
  cat("\n Elasticity of total output w.r.t. ... \n")
  print(getElasticityOutputAccessibility(simulateEconomyInput(), input$sigma), digits = digits)
  cat("\n Equivalent variation approximation \n")
  print(getEquivalentVariation(simulateEconomyInput(), parameters$delta), digits = digits) 
  cat("\n ROAH benefits with WEI \n")
  print(getROAHBenefitsWithTax(simulateEconomyInput(), parameters$tau), digits = digits)
  cat("\n Differences in the economy from a top-down point of view \n")
  print(getTopDownBenefits(simulateEconomyInput(), parameters$tau), digits = digits) 
  cat("\n Rank of scenarios \n")
  print(getRanking(simulateEconomyInput(), parameters$tau), digits = digits)
  cat("\n Averages \n")
  print(getAverages(simulateEconomyInput()), digits = digits)
  cat("\n Logit Transport Model \n")
  print(getLogitTransportModel(simulateEconomyInput(), input$sigma), digits = digits) 
  cat("\n Inequality measures, post-taxation \n")
  print(getIneq(simulateEconomyInput(), parameters$tau), digits = digits) 
})

output$summary_economy_fixed <- renderPrint({
  if (is.null(simulateEconomyFixedInput())) return(invisible(NULL))
  digits <- 4
  cat("[FIXED LAND-USE RESULTS] \n \n")
  if (input$showConvergenceMessage) getConvergenceMessages(simulateEconomyFixedInput())
  cat("\n Elasticities of VKT w.r.t. ... \n")
  print(getVKTAccessibility(simulateEconomyFixedInput()), digits = digits)
  cat("\n Elasticity of total output w.r.t. ... \n")
  print(getElasticityOutputAccessibility(simulateEconomyFixedInput(), input$sigma), digits = digits) 
  cat("\n Equivalent variation approximation \n")
  print(getEquivalentVariation(simulateEconomyFixedInput(), parameters$delta), digits = digits) 
  cat("\n ROAH benefits with WEI \n")
  print(getROAHBenefitsWithTax(simulateEconomyFixedInput(), parameters$tau), digits = digits)
  cat("\n Differences in the economy from a top-down point of view \n")
  print(getTopDownBenefits(simulateEconomyFixedInput(), parameters$tau), digits = digits)  
  cat("\n Rank of scenarios \n")
  print(getRanking(simulateEconomyFixedInput(), parameters$tau), digits = digits)
  cat("\n Averages \n")
  print(getAverages(simulateEconomyFixedInput()), digits = digits)
  cat("\n Logit Transport Model \n")
  print(getLogitTransportModel(simulateEconomyFixedInput(), input$sigma), digits = digits) 
  cat("\n Inequality measures, post-taxation \n")
  print(getIneq(simulateEconomyFixedInput(), parameters$tau), digits = digits)
})