library(shiny)
library(BB)
library(igraph)
library(plyr)
library(deldir)
library(truncdist)
library(lattice)
library(fields)
library(mgcv)
library(arrayhelpers)
library(plotrix)
library(akima)
library(plot3D)
library(tidyr)
library(ggplot2)
library(ineq)
library(shinythemes)
library(RColorBrewer)
library(reshape2)
library(gtools)
library(abind)

source("data.R")
source("city.R")
source("population.R")
source("utility.R")
source("probability.R")
source("spillover.R")
source("simulation.R")
source("economy.R")
source("helpers.R")

shinyServer(
  function(input, output, session) {
    source("reactives.R", local = TRUE)
    source("plots.R", local = TRUE)
    source("prints.R", local = TRUE)
    source("tables.R", local = TRUE)
  }
)